### ISSUE TITLE
[WinUI] FontAwesome is not beeing rendered

### ISSUE THREAD

**Issue by dojo90** [MartinTopfstedt/FontAwesome6#17]
Seems to be the same issue like https://github.com/MartinTopfstedt/FontAwesome6/issues/9 but with WinUI

```xaml
  xmlns:fonts="using:FontAwesome6.Fonts"
  mc:Ignorable="d"
  Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

  <StackPanel Orientation="Vertical" Spacing="20">
    
    <fonts:FontAwesome Icon="Solid_TriangleExclamation" />
    <FontIcon FontFamily="Segoe UI Emoji" Glyph="&#x1F514;" />
  </StackPanel>
```

![grafik](https://user-images.githubusercontent.com/17551597/167594221-281455b9-d2b9-4cd1-b808-ef8c3822172b.png)

***.csproj**
```xml
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows10.0.18362.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.18362.0</TargetPlatformMinVersion>
    <RootNamespace>HtSuite.WinUI.Leitstand</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;arm64</Platforms>
    <RuntimeIdentifiers>win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>
    <PublishProfile>win10-$(Platform).pubxml</PublishProfile>
    <UseWinUI>true</UseWinUI>
    <EnablePreviewMsixTooling>true</EnablePreviewMsixTooling>
    <WindowsPackageType>None</WindowsPackageType>
    <SupportedOSPlatformVersion>10.0.18362.0</SupportedOSPlatformVersion>
  </PropertyGroup>
```

**Comment by dojo90** [comment]
I already use v2.0.4

**Comment by myblindy** [comment]
Hi, I'm having the same issue with 2.0.6 and WinUI 3. 1.1.1. 

```cs
<fa6:FontAwesome Icon="Solid_CodeBranch"/>
```

displays a box:

![image](https://user-images.githubusercontent.com/541998/176952465-392ba531-c76c-4c1c-93c3-49a3df8a5cb7.png)

**Comment by MartinTopfstedt** [comment]
Hi, i will try to find a solution. Culd you provide your .csproj settings?

**Comment by MartinTopfstedt** [comment]
Hi, Please use the new FontAwesom6.Fonts.WinUI / FontAwesome6.Svg.WinUI Packages.

**Comment by myblindy** [comment]
Hm, is this supposed to compile when used? I'm getting XAML parsing failed exceptions when I try to use it:

![image](https://user-images.githubusercontent.com/541998/177045722-63a176a2-549d-42c6-a56b-d786c3ac6da6.png)

With the following code:

```cs
<Page
    x:Class="Gitsie.Views.RepositoryPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
    xmlns:viewmodels="using:Gitsie.ViewModels" 
    xmlns:fa="using:FontAwesome"
    xmlns:fa6="using:FontAwesome6.Fonts"
    d:DataContext="{d:DesignInstance Type=viewmodels:RepositoryViewModel}"
    mc:Ignorable="d">

    <Grid x:Name="ContentArea">
        <Grid.RowDefinitions>
            <RowDefinition Height="auto"/>
            <RowDefinition Height="*"/>
        </Grid.RowDefinitions>

        <fa6:FontAwesome Grid.Row="1" Icon="Regular_ClosedCaptioning"/>
    </Grid>
</Page>
```

Could you provide an example that actually uses the nuget package, please? The example in this repository just hard includes the project itself, and I'm fairly sure it's the nuget package that was and is still borked. 

I'll keep using a normal `FontIcon` for now with my own glyph bindings, but please let me know when you have a sample that works, I'll take a look at this again.

**Comment by MartinTopfstedt** [comment]
Hi, yes the nuget package was the problem, i attached an example project.
(https://github.com/MartinTopfstedt/FontAwesome6/files/9035159/FontAwesome6.WinUI.Examples.zip)
t

**Comment by myblindy** [comment]
> Hi, yes the nuget package was the problem, i attached an example project. (https://github.com/MartinTopfstedt/FontAwesome6/files/9035159/FontAwesome6.WinUI.Examples.zip)

So this works, and the only differences I see are that your example is an unpackaged application, and this part here:

```xml
  <Target Name="_RemoveFrameworkReferences" BeforeTargets="_ConvertItems;_CalculateInputsForGenerateCurrentProjectAppxManifest">
    <ItemGroup>
      <FrameworkSdkReference Remove="@(FrameworkSdkReference)" Condition="$([System.String]::Copy('%(FrameworkSdkReference.SDKName)').StartsWith('Microsoft.WindowsAppRuntime.'))" />
    </ItemGroup>
  </Target>
```

In a packaged application that disables the XAML compiler, which triggers another exception, and without it I get the same XAML parsing error as usual.

**Comment by MartinTopfstedt** [comment]
Could you provide a minimal example project?

**Comment by myblindy** [comment]
Sure, here you go: https://github.com/myblindy/fa6-winui-xaml-parsing-error-demo

It's just the default WinUI Template Studio project, with a nuget reference to this project.

**Comment by myblindy** [comment]
Just so we're 100% on the same page, build and run the above project as x64 (or x86, both have the same problem) as a packaged application. Git doesn't store the active configuration so you're likely to get Any Cpu by default, something I'd fix in a production repo, but I wanted to keep this with as little changes from the default template as necessary.

**Comment by MartinTopfstedt** [comment]
ok, i guess i fixed it. Please try version v2.2.0.
