### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by cptalpdeniz** [MartinTopfstedt/FontAwesome6#37]
First of all, thank you! I'm trying to use this but this is not very straight forward. There is no clear step-by-step installation. Readme is very comprehensive but it's also confusing. There is multiple methods overlapping with each other. Pretending that installation was successful, how can I use this as icon? Especially for <FontIcon> or <ImageIcon>? As trying to use the glyphs didn't work, I looked for alternatives and found this however I don't understand how to use it. Readme says check examples for advanced usage, the examples are very shorts and don't work.

**Comment by MartinTopfstedt** [comment]
Hi, what nuget package do you use?

**Comment by cptalpdeniz** [comment]
I've used the `FontAwesome6.Pro.Fonts` nuget package.

**Comment by MartinTopfstedt** [comment]
ok, i assume you are using .Net with WPF.

- Did you download the Web Version of the FontAwesome Pro Icons?
- Did you copy the *.ttf fonts into your project and included them as "Content" and "Copy Always" https://github.com/MartinTopfstedt/FontAwesome6/blob/5b59c2aafadc99e41e47750f155f7bfc90fe46b8/src/FontAwesome6.Example.NetCore/FontAwesome6.Example.WPF.NetCore.csproj#L29-L49
- Did you add the loading of the *.ttf file to you App class? (https://github.com/MartinTopfstedt/FontAwesome6#load-the-font-files-from-the-file-system)

If all this has been done right the icons are shown when you run the program, they are not shown in Visual Studio. For that you need do this: https://github.com/MartinTopfstedt/FontAwesome6#load-icons-inside-designer.

**Comment by cptalpdeniz** [comment]
I did all of this however it still did not work. In fact, I had multiple issues so I dropped FontAwesome support completely. Thank you for your help Martin! I'm closing this issue.
