### ISSUE TITLE
...type 'fa:SvgAwesome' and ...type faf:FontAwesome" not found

### ISSUE THREAD

**Issue by GFNiko** [MartinTopfstedt/FontAwesome6#39]
Trying to use FontAwesome 6 in my WinUI 3 project. But I can't get it to run. I installed the packages of svg and / or fonts via NuGet
from youtr installation guides

The error message and code:
![errors](https://github.com/MartinTopfstedt/FontAwesome6/assets/114079308/a7271bab-41d5-4257-892e-72371ca2c52d)

I installed all of those together and each on on their own
- FontAwesome6.Fonts.WinUI
- FontAwesome6.Fonts
- FontAwesome6.Svg.WinUI
- FontAwesome6.Svg
and tried to fit the xmlns:fa address accordingly.
I restarted Visual Studio multiple times, but I could not bring it to work

![Proof](https://github.com/MartinTopfstedt/FontAwesome6/assets/114079308/1c9b16b1-2973-4d39-87dd-f0c5efcd547f)

MS WIndows 11 Pro 22H2
MS Visual Studio Community 2022 (64-bit) 17.6.4
net6.0-windows10.0.19041.0

**Comment by ip2x** [comment]
I face the same issue. 
Any news about this one ?

**Comment by SharpDevSa** [comment]
The "Using" import helped me to solve this problem for WinUI 3 

xmlns:fas="using:FontAwesome6.Svg"

**Comment by gakera** [comment]
> The "Using" import helped me to solve this problem for WinUI 3
> 
> xmlns:fas="using:FontAwesome6.Svg"

Same, I described how I got it working here: https://github.com/MartinTopfstedt/FontAwesome6/issues/18#issuecomment-1690051779
