### ISSUE TITLE
DevExpress XAML designer issue

### ISSUE THREAD

**Issue by wonea** [MartinTopfstedt/FontAwesome6#7]
Thanks for the new FA6 package, much appreciated.

I've use DevExpress controls extensively, and got my application up and running fine. However I'm getting a XAML designer errors because of the changes to the ImageSourceConverter.

![image](https://user-images.githubusercontent.com/557192/163002877-120dc1d6-62eb-4260-9b25-506a3c838186.png)

![image](https://user-images.githubusercontent.com/557192/163001333-911d9d2f-edb6-4588-924d-d986113f4c4d.png)

![image](https://user-images.githubusercontent.com/557192/163001037-53f71b30-e17c-4e79-963e-e99667d5e91f.png)

Is there a way around this? Should I create my own ImageSourceConverter which inherits MarkupExtension like FA5 does?

FA6
![image](https://user-images.githubusercontent.com/557192/163001789-1140cee6-4dc5-49fb-a7c4-45220a17ff78.png)

FA5
![image](https://user-images.githubusercontent.com/557192/163002578-c31542a6-e1cf-42bb-a572-b5590125fdf7.png)

**Comment by MartinTopfstedt** [comment]
Hi,  you are using a Light Theme icon which is from FontAwesome Pro. Did you create and load the SVG Data in your App.xaml?

**Comment by wonea** [comment]
Closing, I've rolled my own converter
