### ISSUE TITLE
Font doesn`t works

### ISSUE THREAD

**Issue by EmptyChapter** [MartinTopfstedt/FontAwesome6#9]
I met problem with free font version on .NET 6.0. I``ve done everything like in tutorial, but icons don`t want to appear
xmlns link:
![image_2022-04-23_201031873](https://user-images.githubusercontent.com/70898552/164911968-663bc251-5c2f-4813-940e-7ec016e5f75b.png)
Button front:
![image_2022-04-23_201000060](https://user-images.githubusercontent.com/70898552/164911957-4ea59b28-7c61-4645-8c0c-bb1a46b9cb0f.png)
Runtime result:
![image_2022-04-23_200906401](https://user-images.githubusercontent.com/70898552/164911926-00448f09-fbfb-4ee0-b63d-67b487125a4c.png)

**Comment by MartinTopfstedt** [comment]
Hi,

Are you using WPF? Have you tried it without the Style?

**Comment by EmptyChapter** [comment]
Yes, I'm using WPF and i tried without the style. Also i tried it on a new empty project, but it didn't work either

**Comment by EmptyChapter** [comment]
And also, all your regular font controls works, the problem occurs only with attached properties

**Comment by MartinTopfstedt** [comment]
ok, thanks for the information. I will look into this.

**Comment by MartinTopfstedt** [comment]
could you try v2.0.0?

**Comment by EmptyChapter** [comment]
Doesn't work either, same problem

**Comment by MartinTopfstedt** [comment]
Hi, i just create a new WPF .Net 6 project and just added the FontAwesome6.Fonts (2.0.0) Nuget Package and added a button with the attached property and it worked. See attached example:
[WpfApp1.zip](https://github.com/MartinTopfstedt/FontAwesome6/files/8550255/WpfApp1.zip)
.

**Comment by EmptyChapter** [comment]
Yeah, now everything`s fine. Thanks
